name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons libncurses5-dev libncursesw5-dev zlib1g-dev cmake build-essential \
          libsqlite3-dev libffi-dev libssl-at10 libssl-dev autoconf automake libtool pkg-config

      - name: Install Python Tools
        run: |
          pip install --upgrade pip
          pip install buildozer cython flet

      - name: Build APK
        run: |
          buildozer init
          # Настройка конфига
          sed -i 's/requirements = python3,kivy/requirements = python3,flet,flet_audio,pyjnius/' buildozer.spec
          sed -i 's/p4a.bootstrap = sdl2/p4a.bootstrap = webview/' buildozer.spec
          sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET,MODIFY_AUDIO_SETTINGS/' buildozer.spec
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,mp3/' buildozer.spec
          sed -i 's/android.api = 31/android.api = 33/' buildozer.spec

          # Принятие лицензий без Broken Pipe
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          expect -c "
          spawn buildozer -v android debug
          expect \"Accept? (y/N):\" { send \"y\r\"; exp_continue }
          interact
          " || buildozer -v android debug --accept-sdk-license
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-messenger-app
          path: bin/*.apk
